name: Deploy my lambda function
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install libraries
        shell: bash
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt ] then; 
            pip install -r requirements.txt .
          fi

      - name: Create zip bundle
        shell: bash
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
          
  
    
